### ISSUE TITLE
Error: Uncaught [TypeError: numStr.indexOf is not a function]

### ISSUE THREAD

**Issue by sibelius** [s-yadav/react-number-format#412]
I'm getting the following error after upgrading to latest version of react-number-format

```jsx
Error: Uncaught [TypeError: numStr.indexOf is not a function]
at NumberFormat.formatAsNumber (react-number-format/lib/number_format.js:498:40)
  at NumberFormat.formatNumString (react-number-format/lib/number_format.js:539:31)
  at NumberFormat.formatValueProp (react-number-format/lib/number_format.js:581:51)
  at new NumberFormat (react-number-format/lib/number_format.js:106:32)
```

should we check if `numStr` is a string?

**Comment by sibelius** [comment]
it was a wrong usage
